### ISSUE TITLE
why download err

### ISSUE THREAD

**Issue by daofeng2015** [akbaryahya/DockerGS#27]
![IMG_20220613_155043](https://user-images.githubusercontent.com/14891398/173305805-692a3a70-7897-44ef-bf1f-3b43aa9464e7.jpg)
![IMG_20220613_155015](https://user-images.githubusercontent.com/14891398/173305821-8e729616-c475-45bc-afd1-d8abd626cddd.jpg)
open tcp.80.443 udp.22102

**Comment by akbaryahya** [comment]
this is related to proxies
