### ISSUE TITLE
grasscutter.Grasscutter EOF detected.

### ISSUE THREAD

**Issue by xiazeyu** [akbaryahya/DockerGS#30]
Same with https://github.com/Grasscutters/Grasscutter/issues/1014
https://github.com/Grasscutters/Grasscutter/issues/758
https://github.com/Grasscutters/Grasscutter/issues/508

modifying config.json is fine, but I don't know if it is better to have someway to solve it by Container Args.

Also, I am now using TrueNAS Scale, and I encountered some weird startup issue, so my current settings need to be:

![image](https://user-images.githubusercontent.com/10560038/176118993-ebb430cf-e149-4daf-b298-10cc41f98aee.png)

And also cause the Dockerfile is now invisable, maybe more detailed HELP can be priovided?

eg. instead of `-l	Server Language and includes commands`, it is better to say `-l Server Language and includes commands -l 'zh_CN'` or something.

**Comment by louis000008** [comment]
> 与[Grasscutters/Grasscutter#1014 ](https://github.com/Grasscutters/Grasscutter/issues/1014) [Grasscutters/Grasscutter#758 ](https://github.com/Grasscutters/Grasscutter/issues/758) [Grasscutters/Grasscutter#508 相同](https://github.com/Grasscutters/Grasscutter/issues/508)
> 
> 修改 config.json 是可以的，但我不知道有没有办法通过 Container Args 来解决它是否更好。
> 
> 另外，我现在正在使用 TrueNAS Scale，我遇到了一些奇怪的启动问题，所以我当前的设置需要是：
> 
> ![图片](https://user-images.githubusercontent.com/10560038/176118993-ebb430cf-e149-4daf-b298-10cc41f98aee.png)
> 
> 并且还导致 Dockerfile 现在是不可见的，也许可以提供更详细的帮助？
> 
> 例如。而不是`-l Server Language and includes commands`，最好说`-l Server Language and includes commands -l 'zh_CN'`什么。
我也如此 请问具体要修改 config.json 中的哪个位置？谢谢！

**Comment by louis000008** [comment]
I resolved the problem throught modify Grasscutter.java startConsole().
catch (EndOfFileException e) { if(input.length()!=0){ Grasscutter.getLogger().info("EOF detected."); } continue; }

按照这个可以修复

**Comment by akbaryahya** [comment]
This problem should have been resolved a long time ago but I forgot to close it, so if it's still a problem please open it again ;)
